name: Deploy to Hostinger

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-postpilot
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to Hostinger
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start ssh-agent and add private key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Ensure known_hosts for the server (adds host key)
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.HOSTINGER_HOST }}" >> ~/.ssh/known_hosts || true
        env:
          HOSTINGER_HOST: ${{ secrets.HOSTINGER_HOST }}

      - name: "Configure SSH"
        env:
            SSH_USER: ${{ secrets.HOSTINGER_USER }}
            SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            SSH_HOST: ${{ secrets.HOSTINGER_HOST }}
            SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
            mkdir -p ~/.ssh/
            echo "$SSH_KEY" > ~/.ssh/external-machine.key
            chmod 600 ~/.ssh/external-machine.key
            cat >>~/.ssh/config <<END
            Host external-machine
                    HostName $SSH_HOST
                    User $SSH_USER
                    Port $SSH_PORT
                    IdentityFile ~/.ssh/external-machine.key
                    StrictHostKeyChecking no

      - name: Remote deploy (VIA SSH)
        env:
            DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          ssh external-machine 'cd /var/www/postpilot && bin/deploy'
          echo "Deploy finalizado com sucesso!"